export { FranklyProvider } from "./components/FranklyProvider";
export { useReviews } from "./hooks/useReviews";
export { useReviewStats } from "./hooks/useReviewStats";
export { useSubmitReview } from "./hooks/useSubmitReview";
export { ReviewList } from "./components/ReviewList";
export { ReviewForm } from "./components/ReviewForm";
export { StarRating } from "./components/StarRating";
export { StarBadge } from "./components/StarBadge";
export { getStrings, widgetStrings } from "./i18n";
export type { SupportedLocale } from "./i18n";
